# Generated by Django 5.0 on 2025-06-06 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_likes_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='social.post'),
        ),
    ]
