# Generated by Django 5.0 on 2025-06-07 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_likes_id_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_seguido', to=settings.AUTH_USER_MODEL)),
                ('id_seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_seguidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
