# Generated by Django 5.0 on 2025-06-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_followers_id_seguido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pictures_posts/%Y/%m'),
        ),
    ]
